# -*- coding: utf-8 -*-
"""Proyecto-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bIUlpagiD1oe6ciw3kPxswJvSaeZZEY

<a href="https://www.inove.com.ar"><img src="https://raw.githubusercontent.com/InoveAlumnos/dataset_analytics_python/master/images/PA%20Banner.png" width="1000" align="center"></a>


# Proyectos

Proyectos propuestos para Python Analytics<br>
v1.5

### Formato de entrega
Toda la etapa de entrenamiento del proyecto se debe realizar en un colab o nootebook que luego el alumno subierá a su repositorio de proyecto para que el profesor pueda evaluar los avances.<br>

__APROBACIÓN:__ El proyecto será aprobado cuando el modelo entrenado alcance la exactitud/condición planteada en el proyecto.<br>

### Predicción de enfermedades cardíacas
<img src="https://github.com/InoveAlumnos/proyecto_analytics_python/raw/main/heart.png" width="300" align="center">

- El objetivo es armar un clasificador binario que permita predecir si un paciente podría presentar o no enfermedades cardíacas.
- Deberá entrenar un modelo clasificador y varios algoritmos para clasificación. Por ejemplo, en el caso de seleccionar un RandomForest debe entrenar con distinto número de estimadores (distantas cantidad de árboles), pero a su vez entrenar distintos KNN o regresión logística, etc. Deberá compararlos utilizando la métrica adecuada y elegir el mejor modelo.
- Entre el dataset encontrará datos categóricos que requieren ser codificados, y datos numéricos para normalizar.
- A modo de análisis, debe identificar si el dataset se encuentra correctamente balanceado (entre pacientes con y sin enfermedad cardíaca), y como está balanceado el dataset en cuanto a género y edad (este análisis es unicamente a modo informativo).

#### Objetivo

El accuracy del modelo definitivo debe superar el 80% (0.8)

Celda 1: Librerías y Configuración
"""

import os
import platform
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Configuración visual Blanco y Negro
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.edgecolor'] = 'black'
plt.rcParams['axes.facecolor'] = 'white'
plt.rcParams['xtick.color'] = 'black'
plt.rcParams['ytick.color'] = 'black'
plt.rcParams['text.color'] = 'black'
plt.rcParams['axes.labelcolor'] = 'black'
plt.rcParams['image.cmap'] = 'Greys'

print("-"*70,"\nHecho: liberías importadas.")

"""Celda 2: Descarga de Datos"""

if os.access('heart.csv', os.F_OK) is False:
    if platform.system() == 'Windows':
        !curl https://raw.githubusercontent.com/InoveAlumnos/dataset_analytics_python/master/heart.csv > heart.csv
    else:
        !wget heart.csv https://raw.githubusercontent.com/InoveAlumnos/dataset_analytics_python/master/heart.csv

print("-"*70,"\nHecho: dataset descargado.")

"""Celda 3: Carga y Exploración"""

df = pd.read_csv('heart.csv')

print("Información del dataset:")
print(df.info())
print("\nPrimeras filas:")
display(df.head())

print("-"*70,"\nHecho: datos cargados y verificados.")

"""Celda 4: Preprocesamiento y Split"""

# 1. Definimos X e y
X = df.drop('target', axis=1)
y = df['target']

# 2. Separamos columnas numéricas y categóricas
# 'thal', 'slope', 'ca' son categóricas, no numéricas.
cat_cols = ['cp', 'restecg', 'slope', 'ca', 'thal', 'sex', 'fbs', 'exang']
num_cols = [c for c in X.columns if c not in cat_cols]

# 3. Pipelines de transformación
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ])

# 4. Split Estratificado (Clave para superar el 85%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Train: {X_train.shape}, Test: {X_test.shape}")
print("-"*70,"\nHecho: preprocesamiento configurado y datos divididos.")

"""Celda 5: Configuración de Modelos (Grid)"""

# Diccionario de configuración de modelos
grid_cfg = {
    'RandomForest': (RandomForestClassifier(random_state=42),
           {'clf__n_estimators': [100, 200],
            'clf__max_depth': [5, 10, None],
            'clf__min_samples_leaf': [1, 2],
            'clf__criterion': ['gini', 'entropy']}),

    'KNN': (KNeighborsClassifier(),
            {'clf__n_neighbors': [3, 5, 7, 11, 15],
             'clf__weights': ['uniform', 'distance'],
             'clf__metric': ['euclidean', 'manhattan']}),

    'LogisticRegression': (LogisticRegression(max_iter=1000, solver='liblinear', random_state=42),
            {'clf__C': [0.1, 1, 5, 10],
             'clf__penalty': ['l1', 'l2']})
}

print("-"*70,"\nHecho: grilla de hiperparámetros definida.")

"""Celda 6: Entrenamiento y Selección"""

best_acc = 0
best_model = None
best_name = ""

print(f"{'Modelo':<20} | {'CV Score':<10} | {'Test Accuracy':<10}")
print("-" * 50)

for name, (est, params) in grid_cfg.items():
    # Pipeline: Preproceso + Modelo
    pipe = Pipeline([('prep', preprocessor), ('clf', est)])

    # GridSearch
    grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy', n_jobs=-1)
    grid.fit(X_train, y_train)

    # Evaluar en Test
    y_pred = grid.best_estimator_.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"{name:<20} | {grid.best_score_:.4f}     | {acc:.4f}")

    # Guardar el mejor
    if acc > best_acc:
        best_acc = acc
        best_model = grid.best_estimator_
        best_name = name

print("-" * 50)
print(f"Mejor modelo: {best_name} con {best_acc:.2%} de Accuracy")
print("-"*70,"\nHecho: modelos entrenados y evaluados.")

"""Celda 7: Visualización Final (B&N)"""

from sklearn.model_selection import learning_curve

# 1. Predicciones y Métricas Finales
y_pred_final = best_model.predict(X_test)
acc_final = accuracy_score(y_test, y_pred_final)
cm = confusion_matrix(y_test, y_pred_final)

# Configuración del panel (3 gráficos en fila)
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
plt.subplots_adjust(wspace=0.3)

# --- GRÁFICO 1: Matriz de Confusión ---
sns.heatmap(cm, annot=True, fmt='d', cmap='Greys', cbar=False,
            xticklabels=['Sano', 'Enfermo'], yticklabels=['Sano', 'Enfermo'],
            linewidths=2, linecolor='black', ax=axes[0])
axes[0].set_title(f'1. Matriz de Confusión\n({best_name})', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Predicho')
axes[0].set_ylabel('Real')

# --- GRÁFICO 2: Meta vs Realidad (Barras) ---
metas = ['Meta (85%)', f'Logrado ({acc_final:.1%})']
valores = [0.85, acc_final]
colores = ['silver', 'black'] # Gris claro para la meta, Negro para el logro

bars = axes[1].bar(metas, valores, color=colores, edgecolor='black', linewidth=1.5)
axes[1].set_ylim(0, 1.0)
axes[1].axhline(0.85, color='black', linestyle='--', linewidth=1) # Línea de meta
axes[1].set_title('2. Cumplimiento de Objetivo', fontsize=12, fontweight='bold')
axes[1].bar_label(bars, fmt='%.2f', padding=3, fontsize=11, fontweight='bold')

# --- GRÁFICO 3: Curva de Aprendizaje (Evolución) ---
# Esto calcula cómo mejora el modelo al ver más datos (10% al 100% del train set)
train_sizes, train_scores, test_scores = learning_curve(
    best_model, X_train, y_train, cv=5, n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5), scoring='accuracy'
)

train_mean = np.mean(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)

axes[2].plot(train_sizes, train_mean, 'o--', color='gray', label='Entrenamiento')
axes[2].plot(train_sizes, test_mean, 's-', color='black', linewidth=2, label='Validación (Test)')
axes[2].set_title('3. Evolución del Aprendizaje', fontsize=12, fontweight='bold')
axes[2].set_xlabel('Tamaño del Dataset (Ejemplos)')
axes[2].set_ylabel('Accuracy')
axes[2].legend(loc='lower right')
axes[2].grid(True, linestyle=':', alpha=0.6)

plt.show()

# Mensaje final crudo
print("-" * 70)
if acc_final > 0.85:
    print(f"RESULTADO: {acc_final:.2%} (eficaz).")
else:
    print(f"RESULTADO: {acc_final:.2%} (ineficaz).")
print("-" * 70)
print("Hecho: Visualización, métricas y evolución generadas.")